### ISSUE TITLE
Make openEHR MPI-ID path a changeable property 

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#121]
Currently the openEHR MPI-ID path is set as a hard coded string to `e/ehr_status/subject/external_ref/id/value`. This value should be changeable as a property of the BPE.

**Comment by hhund** [comment]
I think it's even worse since the medic pseudonymization code currently uses `/ehr_id/value` defined in https://github.com/highmed/highmed-dsf/blob/76ecdc50b48cfa1a7ce5f8d0138edd8accd74ec6/dsf-pseudonymization/dsf-pseudonymization-base/src/main/java/org/highmed/pseudonymization/openehr/Constants.java#L6
We should definitely fix this issue for the next release.

**Comment by wetret** [comment]
I adapted the path in the `Local Service Integration` branch to https://github.com/highmed/highmed-dsf/blob/55591a730203105c8e204833212d30a46756586c/dsf-pseudonymization/dsf-pseudonymization-base/src/main/java/org/highmed/pseudonymization/openehr/Constants.java
This should work for the HiGHmed openEHR templates. 

I will try to make it a changeable property in the next step.
