### ISSUE TITLE
Passwords cannot be set as docker secrets when using clients in (process) plugins

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#238]
Passwords cannot be set as docker secrets when using clients in (process) plugins. Passwords have to be set directly as environment variables.

**Comment by hhund** [comment]
Effected Version: 0.5.0-RC1, 0.5.0-RC2

Password properties need to end in `....password` in order to be set by supplying docker secret files via environment variables in the form of `..._PASSWORD_FILE`. Underscore character `_` are not allowed in property names. Currently properties defined via docker secret files are not supplied to process plugins.

https://github.com/highmed/highmed-dsf/blob/2c37bcaafae361c3b86237368fe5426a429b38bf/dsf-bpe/dsf-bpe-server/src/main/java/org/highmed/dsf/bpe/plugin/ProcessPluginDefinitionAndClassLoader.java#L66-L78

The environment of the process plugin context needs to be set from the main context.
