### ISSUE TITLE
Old certificate thumbprint still persisted after renewal

### ISSUE THREAD

**Issue by bauerjs1** [highmed/highmed-dsf#361]
Hi there,

thanks for updating my certificate SHA in the GTH-allow-list! After exchanging the client certificate locally, I still got some warnings about an unknown thumbprint (the old one). Just to note, I am not sure how much of an issue this is, because I was struggling with different things at the same time.

Since I did not have the old thumbprint left in any configuration parameters/files, I believe it was still persisted somewhere in the database. A complete teardown of the (test 😉) environment, including the DB volume, and re-install with the same configuration solved it for now.

I guess, some deletion feature in the DB is missing here. Or does the thumbprint need to be persisted in the DB anyway, if it is specified in the ENVs?

Cheers,
Johannes

**Comment by hhund** [comment]
Hi Johannes,

the thumbprint of your organizations main client-certificate, meaning the client-certificate that your organization uses via the DSF to authenticate against DSF FHIR servers from other organizations e.g. the GECCO Transfer Hub, needs to be part of the Organization FHIR resource for your organization not only as part of the "allow-list" at other organization but also as part of your own allow-list. Since the environment variable [ORG_HIGHMED_DSF_FHIR_SERVER_USER_THUMBPRINTS](https://github.com/highmed/highmed-dsf/wiki/DSF-0.7.0-Configuration-Parameters-FHIR#org_highmed_dsf_fhir_server_user_thumbprints) can be used to privately define additional thumbprints, you could configure a bad thumbprint as part of your allow-list and still be able to access your own DSF FHIR server.

Within the default NUM-CODEX configuration for non HiGHmed organizations, the Organization resource for your own organization is supplied to your local database via the `/opt/fhir/conf/bundle.xml` file on startup of the DSF FHIR server. The entries of that transaction bundle are configured as conditional updates, meaning that the will perform an update on the database on every restart.
Within that file the thumbprint is inserted via property substitution and the substituted value needs to be configured via the environment variable `ORG_HIGHMED_DSF_FHIR_SERVER_ORGANIZATION_THUMBPRINT`.  
In case you have to change your client certificate the variable needs to change as well, which of course means that the docker container needs to be re-created (down / up).

Let me know if this explains the existence of the old thumbprint. I'd guess you did not re-created the container after modifying the environment variables.

**Comment by bauerjs1** [comment]
Hi Hauke,

I can confirm the container was re-created after updating the certificate files and thumbprint (`docker-compose up` does that automatically when it detects changes in the service configurations).

We are using the default non-HiGHmed CODEX configuration which populates the ENVs into the bundle.
