### ISSUE TITLE
Can custom template variables be introduced in bundle.xml?

### ISSUE THREAD

**Issue by bauerjs1** [highmed/highmed-dsf#368]
Hi, me again 😉 

I have a question regarding the CODEX DSF-Deployments. As of now, we use a separate bundle.xml config file for the test and productive deployments each. If I am not mistaken, the only difference is in the certificate thumbprints from Heilbronn. Since you have nicely templated all the other configuration keys in this file via ENVs, I thought this could also be used to mitigate the only difference here, so we can use a single template file and achieve the rest through environment variables only.

So my two questions are:
- Could this be introduced in the example deployments within the next few version upgrades?
- And more importantly: Is this already achievable in our own deployments or does it require some slight code changes in the application?

Thanks in advance and greetings from Erlangen,
Johannes

**Comment by hhund** [comment]
Hi @bauerjs1,

thank you for the suggestion, I will think about introducing additional variables with the next release. But since there are **five** elements that differ between the `bundle.xml` files of the test and production environments (Lines: 103, 136, 143, 156 and 161), this may introduce too much clutter to the docker-compose file and increase the risk of users configuring bad values.

If you want you can introduce your own environment variables and use them as properties in the external `bundle.xml` file. A property placeholder within the `bundle.xml` file like `${foo.bar}` becomes environment variable `FOO_BAR`.

Best, Hauke

**Comment by bauerjs1** [comment]
Thank you Hauke, I will give this solution a try!

Not sure if I should close this ticket or if you want it to remain open for reference. Feel free to close.

Cheers!

**Comment by hhund** [comment]
Closing the issue as the questions have been answered.
