### ISSUE TITLE
Change Workflow / Branching Model to Git-Flow

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#57]
Maybe we can start developing using the Git-Flow Concept
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by hhund** [comment]
Since version [0.1.0](https://github.com/highmed/highmed-dsf/tree/v0.1.0) is released now, I think its a good time to switch to Git-Flow. I therefore created a [develop](https://github.com/highmed/highmed-dsf/tree/develop) branch for integrating new features and fixes for the next release.

The [develop](https://github.com/highmed/highmed-dsf/tree/develop) branch currently has commits allowed by @wetret and @hhund

New features should branch of develop and merged back if done. Hot-Fixes for the latest release will branch of master and will be merged into master and develop. A new release will branch of develop for a ramp down phase and will than be merged into master. The new master should merge back into develop to start a new development cycle.

@wetret comments, before we write this up in the wiki and close this issue?

**Comment by wetret** [comment]
Sounds reasonable. We can also add the link from above to the wiki.

**Comment by wetret** [comment]
I wrote some lines in the Wiki: [https://github.com/highmed/highmed-dsf/wiki/Writing-Code](https://github.com/highmed/highmed-dsf/wiki/Writing-Code).

@hhund can you make changes and close the issue when the wiki part is fine?

**Comment by hhund** [comment]
Changed branch naming pattern for releases.
